import { readFileSync } from 'node:fs'
import test from 'node:test'
import assert from 'node:assert/strict'

const source = readFileSync(new URL('./test-ui-aks-live-job.sh', import.meta.url), 'utf8')
const liveContainer = source.slice(source.indexOf('        - name: live-test'), source.indexOf('      volumes:', source.indexOf('        - name: live-test')))
const revokeContainer = source.slice(source.indexOf('        - name: revoke'), source.indexOf('      volumes:', source.indexOf('        - name: revoke')))

test('AKS live Job requires explicit dev mutation approval and creates an ephemeral admin key', () => {
  assert.match(source, /UI_LIVE_TEST_APPROVAL/)
  assert.match(source, /I_APPROVE_DEV_AKS_LIVE_MUTATION/)
  assert.match(source, /explicit user authorization is required/)
  assert.match(source, /EXPECTED_CLUSTER_UID/)
  assert.match(source, /Kubernetes cluster identity mismatch/)
  assert.match(source, /LIVE_TEST_IMAGE must be an immutable s3proxy-ui-live-test ACR reference/)
  assert.match(source, /azurecr\\\.io\/s3proxy-ui-live-test@sha256/)
  assert.match(source, /openssl rand -hex 32/)
  assert.match(source, /S3PROXY_E2E_ADMIN_KEY_HASH/)
  assert.match(source, /upsert-e2e-admin-key/)
  assert.match(source, /s3proxy-migrator-secrets/)
  assert.match(source, /APP_MIGRATOR_DATABASE__URL/)
  assert.match(source, /stringData:/)
  assert.match(source, /secretKeyRef: \{name: \$ADMIN_KEY_SECRET, key: \$ADMIN_KEY_FIELD\}/)
    assert.doesNotMatch(source, /issue280|ADMIN_KEY_SECRET="\$\{ADMIN_KEY_SECRET:\?/)
    assert.match(source, /create secret tls "\$TLS_SECRET"/)
    assert.match(liveContainer, /name: tls, mountPath: \/tls, readOnly: true/)
    assert.doesNotMatch(revokeContainer, /mountPath: \/tls/)
    assert.match(source, /https\.createServer/)
    assert.match(source, /spawn\('\.\/node_modules\/\.bin\/playwright'/)
    assert.match(source, /https:\/\/127\.0\.0\.1:8443/)
    assert.match(source, /x-forwarded-proto.*https/i)
    assert.doesNotMatch(source, /host: upstream\.host/)
    assert.match(source, /UI_E2E_CONTROL_BASE_URL/)
})

test('AKS live Job is isolated and always removes credentials and Jobs', () => {
  assert.match(source, /automountServiceAccountToken: false/)
  assert.match(source, /readOnlyRootFilesystem: true/)
  assert.match(source, /capabilities: \{drop: \["ALL"\]\}/)
  assert.match(source, /s3proxy\.rs\/access-ui: "true"/)
  assert.match(source, /response\.status === 204/)
  assert.match(source, /trap cleanup_on_exit EXIT/)
  assert.match(source, /delete job "\$MIGRATOR_JOB"/)
  assert.match(source, /delete job "\$REVOKE_JOB"/)
    assert.match(source, /delete secret "\$ADMIN_KEY_SECRET"/)
    assert.match(source, /delete secret "\$TLS_SECRET"/)
  assert.match(source, /\/admin\/api-keys\/cloud-e2e/)
  assert.match(source, /UI_E2E_BASE_URL, value: "https:\/\/127\.0\.0\.1:8443"/)
  assert.match(source, /UI_E2E_S3_ENDPOINT, value: "\$S3_ENDPOINT"/)
  assert.match(source, /temporary administrator key provisioning failed/)
  assert.match(source, /"4 passed"/)
  assert.ok(source.indexOf('delete job "$JOB_NAME"') < source.indexOf('revoke_admin_key >/dev/null'), 'cleanup must stop tests before revoking credentials')
})