apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: s3proxy
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: s3proxy-ui
    newName: s3proxy-ui
    newTag: split-image-must-be-overridden