import { useState, type FormEvent } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { ChevronLeft, ChevronRight, Eye, Pencil, Trash2, X } from 'lucide-react'
import { api, ApiError } from '../../api/client'
import type { Schema } from '../../api/control'
import { invalidateControl } from '../../api/query-keys'
import { DataTable, DestructiveDialog, ErrorBanner, Modal, RefreshButton } from '../../components/control'
import { bucketPolicyEndpoint, bucketPolicyRequest, formatPolicyDocument, policyKeys, scopeLabel, validationRequest, type BucketPolicyDetail, type PolicyScope } from './policy-state'

type ScopeKind = PolicyScope['kind']

export default function BucketPolicies() {
  const [kind, setKind] = useState<ScopeKind>('direct')
  const [cursors, setCursors] = useState<Array<string | null>>([null])
  const cursor = cursors[cursors.length - 1]
  const list = useQuery({ queryKey: policyKeys.bucketList(cursor), queryFn: () => api<Schema['AdminBucketPolicyPage']>(`/admin/ui/bucket-policies?limit=100${cursor ? `&after_key=${encodeURIComponent(cursor)}` : ''}`) })
  const [scope, setScope] = useState<PolicyScope | null>(null)
  const detail = useQuery({ queryKey: scope ? policyKeys.bucketDetail(scope) : policyKeys.bucketList('detail-disabled'), enabled: scope !== null, queryFn: () => api<BucketPolicyDetail>(bucketPolicyEndpoint(scope!)) })
  const [operation, setOperation] = useState<'edit' | 'delete' | null>(null)
  const rows = list.data?.items.filter(item => item.scope.kind === kind) ?? []
  return <section className="policy-section" aria-labelledby="bucket-policy-title"><div className="section-heading"><div><h2 id="bucket-policy-title">Bucket policies</h2><p>Direct global and credential-scoped virtual policies are separate authorization scopes.</p></div><RefreshButton pending={list.isFetching || detail.isFetching} refresh={() => { void list.refetch(); if (scope) void detail.refetch() }} /></div>
    <div className="scope-switch" role="group" aria-label="Bucket policy scope"><button className={kind === 'direct' ? 'active' : ''} aria-pressed={kind === 'direct'} onClick={() => { setKind('direct'); setCursors([null]); setScope(null) }}>Direct global</button><button className={kind === 'virtual' ? 'active' : ''} aria-pressed={kind === 'virtual'} onClick={() => { setKind('virtual'); setCursors([null]); setScope(null) }}>Virtual scoped</button></div>
    <p className="policy-notice">{kind === 'direct' ? 'Direct policies authorize the global S3 bucket name.' : 'Virtual policies are isolated by stable virtual bucket and owning credential IDs.'} No action here changes Azure containers, blobs, or routing.</p>
    {list.isError && <ErrorBanner error={list.error} retry={() => { void list.refetch() }} />}
    <DataTable rows={rows} loading={list.isPending} rowKey={row => row.scope.kind === 'direct' ? `direct:${row.scope.bucket}` : `virtual:${row.scope.bucket_id}`} columns={[{ label: 'Scope', value: row => scopeLabel(row.scope) }, { label: 'Revision', value: row => row.revision }, { label: 'Updated', value: row => new Date(row.updated_at).toLocaleString() }, { label: 'Actions', value: row => <button className="icon-button" title="View bucket policy" aria-label={`View ${scopeLabel(row.scope)}`} onClick={() => setScope(row.scope)}><Eye size={16} /></button> }]} />
    <div className="policy-pagination"><button className="icon-button" aria-label="Previous bucket policy page" title="Previous page" disabled={cursors.length === 1 || list.isFetching} onClick={() => setCursors(value => value.slice(0, -1))}><ChevronLeft size={16} /></button><span>Page {cursors.length}</span><button className="icon-button" aria-label="Next bucket policy page" title="Next page" disabled={!list.data?.next_after_key || list.isFetching} onClick={() => { if (list.data?.next_after_key) setCursors(value => [...value, list.data!.next_after_key]) }}><ChevronRight size={16} /></button></div>
    {scope && <section className="policy-detail" aria-label="Bucket policy detail"><div className="section-heading"><h2>{scopeLabel(scope)}</h2><button className="icon-button" title="Close detail" aria-label="Close bucket policy detail" onClick={() => setScope(null)}><X size={16} /></button></div>{detail.isError && <ErrorBanner error={detail.error} retry={() => { void detail.refetch() }} />}{detail.isPending && <p role="status">Loading bucket policy...</p>}{detail.data && <><dl className="policy-detail-grid"><dt>Scope kind</dt><dd>{detail.data.policy.scope.kind}</dd><dt>Revision</dt><dd>{detail.data.policy.revision}</dd>{detail.data.policy.scope.kind === 'virtual' && <><dt>Owning credential</dt><dd>{detail.data.policy.scope.credential_id}</dd><dt>Virtual bucket ID</dt><dd>{detail.data.policy.scope.bucket_id}</dd></>}</dl><pre className="policy-document">{formatPolicyDocument(detail.data.document)}</pre><div className="policy-actions"><button onClick={() => setOperation('edit')}><Pencil size={16} />Edit policy</button><button className="danger" onClick={() => setOperation('delete')}><Trash2 size={16} />Delete policy</button></div></>}</section>}
    {operation && detail.data && <BucketPolicyDialog operation={operation} initial={detail.data} close={() => setOperation(null)} changed={next => { setOperation(null); if (!next) setScope(null); void invalidateControlQuery(list.refetch, detail.refetch, next) }} />}
  </section>
}

async function invalidateControlQuery(refetchList: () => unknown, refetchDetail: () => unknown, detail: BucketPolicyDetail | null) { await refetchList(); if (detail) await refetchDetail() }

function BucketPolicyDialog({ operation, initial, close, changed }: { operation: 'edit' | 'delete'; initial: BucketPolicyDetail; close: () => void; changed: (detail: BucketPolicyDetail | null) => void }) {
  const client = useQueryClient()
  const [document, setDocument] = useState(formatPolicyDocument(initial.document))
  const [review, setReview] = useState<BucketPolicyDetail | null>(null)
  const [validation, setValidation] = useState<Schema['AdminPolicyDraftValidationResponse'] | null>(null)
  const [error, setError] = useState<Error | null>(null)
  const [stale, setStale] = useState(false)
  const [pending, setPending] = useState(false)
  async function prepare(event?: FormEvent) { event?.preventDefault(); setPending(true); setError(null); setStale(false); try { if (operation === 'edit') { const result = await api<Schema['AdminPolicyDraftValidationResponse']>('/admin/ui/policies/validate', { method: 'POST', body: JSON.stringify(validationRequest(document, 'bucket_policy')) }); setValidation(result); if (!result.valid) throw new Error('Resolve server validation findings before review') } const authoritative = await api<BucketPolicyDetail>(bucketPolicyEndpoint(initial.policy.scope)); bucketPolicyRequest(authoritative, operation === 'edit' ? document : undefined); setReview(authoritative) } catch (cause) { setError(cause instanceof Error ? cause : new Error('Bucket policy review failed')) } finally { setPending(false) } }
  async function persist() { if (!review || pending) return; setPending(true); setError(null); try { const result = await api<Schema['AdminBucketPolicyMutationResult']>(bucketPolicyEndpoint(review.policy.scope), { method: operation === 'edit' ? 'PUT' : 'DELETE', body: JSON.stringify(bucketPolicyRequest(review, operation === 'edit' ? document : undefined)) }); await invalidateControl(client); changed(result.detail) } catch (cause) { setError(cause instanceof Error ? cause : new Error('Bucket policy change failed')); setReview(null); if (cause instanceof ApiError && cause.status === 409) { setStale(true); await invalidateControl(client) } } finally { setPending(false) } }
  if (operation === 'delete' && review) return <DestructiveDialog title="Delete bucket policy" description={`${scopeLabel(review.policy.scope)}. Permanently removes authorization metadata for this exact scope; Azure storage and routing are unchanged.`} confirmLabel={`Delete policy for ${scopeLabel(review.policy.scope)}`} pending={pending} onClose={() => setReview(null)} onConfirm={() => { void persist() }}><dl className="policy-detail-grid"><dt>Scope</dt><dd>{scopeLabel(review.policy.scope)}</dd><dt>Reviewed revision</dt><dd>{review.policy.revision}</dd></dl>{error && <ErrorBanner error={error} />}</DestructiveDialog>
  return <Modal title={review ? 'Confirm: edit bucket policy' : `${operation === 'edit' ? 'Edit' : 'Delete'} bucket policy`} description={`${scopeLabel(initial.policy.scope)}. Authorization metadata only; Azure storage and routing are unchanged.`} onClose={close} pending={pending}>{error && <ErrorBanner error={error} retry={stale ? () => { void prepare() } : undefined} />}{stale && <p className="policy-notice">Authoritative policy state changed. Your draft is preserved for re-review.</p>}{review ? <><dl className="policy-detail-grid"><dt>Scope</dt><dd>{scopeLabel(review.policy.scope)}</dd><dt>Reviewed revision</dt><dd>{review.policy.revision}</dd>{operation === 'edit' && <><dt>Statements</dt><dd>{validation?.statements ?? 'Unavailable'}</dd><dt>Compiled bytes</dt><dd>{validation?.compiled_bytes ?? 'Unavailable'}</dd></>}</dl><div className="dialog-actions"><button disabled={pending} onClick={() => setReview(null)}>Back</button><button className="primary" disabled={pending} onClick={() => { void persist() }}>{pending ? 'Applying...' : 'Confirm change'}</button></div></> : <form className="operation-form" onSubmit={event => { void prepare(event) }}>{operation === 'edit' ? <><label>Policy document<textarea className="policy-editor" spellCheck={false} value={document} onChange={event => setDocument(event.target.value)} /></label>{validation && !validation.valid && <ul className="policy-violations">{validation.violations.map((item, index) => <li key={`${item.code}-${index}`}>{item.field}: {item.message}</li>)}</ul>}</> : <p>This removes only the policy for this exact {initial.policy.scope.kind} scope.</p>}<div className="dialog-actions"><button type="button" disabled={pending} onClick={close}>Cancel</button><button className={operation === 'delete' ? 'danger' : 'primary'} disabled={pending}>{pending ? 'Refreshing review...' : 'Review change'}</button></div></form>}</Modal>
}