/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["publicHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["controlOpenApi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bootstrap/api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Private control-plane operation. Deployment networking must prevent public access; the data plane does not register this route. */
        post: operations["bootstrapAdminKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/session/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete: operations["logout"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAdminKeys"];
        put?: never;
        post: operations["createAdminKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api-keys/{key_name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_name: components["parameters"]["KeyName"];
            };
            cookie?: never;
        };
        get: operations["getAdminKey"];
        put: operations["updateAdminKey"];
        post?: never;
        delete: operations["deleteAdminKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCredentials"];
        put?: never;
        post: operations["createCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ui/identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listIdentityProjections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/credentials/{access_key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_key: components["parameters"]["AccessKey"];
            };
            cookie?: never;
        };
        get: operations["getCredential"];
        put: operations["updateCredential"];
        post?: never;
        delete: operations["deleteCredential"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/credentials/{credential_id}/rotate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotateCredentialSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/backends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBackends"];
        put?: never;
        post: operations["createBackend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/backends/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        get: operations["getBackend"];
        put: operations["updateBackend"];
        post?: never;
        delete: operations["deleteBackend"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/virtual-buckets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listVirtualBuckets"];
        put?: never;
        post: operations["createVirtualBucket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/virtual-buckets/{bucket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: components["parameters"]["BucketId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["updateVirtualBucket"];
        post?: never;
        delete: operations["deleteVirtualBucket"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPolicies"];
        put?: never;
        post: operations["createPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/policies/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["policyPreflight"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/policies/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        get: operations["getPolicy"];
        put: operations["updatePolicy"];
        post?: never;
        delete: operations["deletePolicy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/credentials/{access_key}/policies": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_key: components["parameters"]["AccessKey"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["attachPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/credentials/{access_key}/policies/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_key: components["parameters"]["AccessKey"];
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["detachPolicy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/buckets/{bucket}/policy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket: components["parameters"]["Bucket"];
            };
            cookie?: never;
        };
        get: operations["getBucketPolicy"];
        put: operations["setBucketPolicy"];
        post?: never;
        delete: operations["deleteBucketPolicy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/virtual-buckets/{bucket_id}/policy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: components["parameters"]["BucketId"];
            };
            cookie?: never;
        };
        get: operations["getVirtualBucketPolicy"];
        put: operations["setVirtualBucketPolicy"];
        post?: never;
        delete: operations["deleteVirtualBucketPolicy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/policy/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["simulatePolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRoles"];
        put?: never;
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        get: operations["getRole"];
        put?: never;
        post?: never;
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles/{role_id}/trust": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["updateRoleTrust"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles/{role_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["updateRoleSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles/{role_id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setRoleEnabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles/{role_id}/retire-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retireRoleSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles/{role_id}/policies": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["attachRolePolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles/{role_id}/policies/{policy_name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: components["parameters"]["RoleId"];
                policy_name: components["parameters"]["PolicyName"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["detachRolePolicy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            Code: string;
            Message: string;
            RequestId?: string;
        };
        /** @description Plain-text Axum extractor rejection; no JSON error envelope is emitted. */
        ValidationError: string;
        JsonValue: unknown;
        LoginRequest: {
            api_key: string;
        };
        LoginResponse: {
            csrf_token: string;
            /** Format: date-time */
            expires_at: string;
        };
        SessionResponse: {
            authenticated: boolean;
            csrf_token: string;
            /** Format: date-time */
            expires_at: string;
        };
        BootstrapAdminKeyRequest: {
            key_name: string;
            description?: string | null;
            /** @default bootstrap */
            created_by: string;
        };
        BootstrapAdminKeyResponse: {
            key_name: string;
            api_key: string;
            warning: string;
        };
        CreateAdminApiKeyRequest: {
            key_name: string;
            description?: string | null;
            expires_in_days?: number | null;
            created_by?: string | null;
        };
        CreateAdminApiKeyResponse: {
            /** Format: uuid */
            id: string;
            key_name: string;
            api_key: string | null;
            description: string | null;
            /** Format: date-time */
            expires_at: string | null;
            /** Format: date-time */
            created_at: string;
            warning: string;
        };
        AdminApiKey: {
            /** Format: uuid */
            id: string;
            key_name: string;
            description: string | null;
            enabled: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at: string | null;
            /** Format: date-time */
            expires_at: string | null;
            created_by: string | null;
        };
        AdminApiKeySummary: {
            /** Format: uuid */
            id: string;
            key_name: string;
            description: string | null;
            enabled: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at: string | null;
            /** Format: date-time */
            expires_at: string | null;
            created_by: string | null;
            status: string;
        };
        AdminApiKeyList: components["schemas"]["AdminApiKeySummary"][];
        UpdateAdminApiKeyRequest: {
            enabled: boolean;
        };
        /** @enum {string} */
        CredentialAccessMode: "direct" | "virtual";
        CreateCredentialRequest: {
            /** @default  */
            s3_access_key: string;
            /** @default  */
            s3_secret_key: string;
            azure_account: string;
            azure_key?: string | null;
            use_managed_identity: boolean;
            credential_scope?: string | null;
            access_mode: components["schemas"]["CredentialAccessMode"];
            versioning_enabled?: boolean | null;
            /** Format: uuid */
            default_backend_id?: string | null;
        };
        UpdateCredentialRequest: {
            s3_secret_key?: string | null;
            azure_account?: string | null;
            azure_key?: string | null;
            use_managed_identity?: boolean | null;
            credential_scope?: string | null;
            access_mode?: components["schemas"]["CredentialAccessMode"] | null;
            versioning_enabled?: boolean | null;
            enabled?: boolean | null;
            /** Format: uuid */
            default_backend_id?: string | null;
        };
        CredentialCreatedResponse: {
            /** Format: uuid */
            credential_id: string;
            s3_access_key: string;
            s3_secret_key: string;
            s3_endpoint: string;
            azure_account: string;
            access_mode: components["schemas"]["CredentialAccessMode"];
            use_managed_identity: boolean;
            /** Format: uuid */
            default_backend_id: string | null;
        };
        CredentialSummary: {
            /** Format: uuid */
            credential_id: string | null;
            s3_access_key: string;
            azure_account: string;
            access_mode: components["schemas"]["CredentialAccessMode"];
            use_managed_identity: boolean;
            versioning_enabled: boolean;
            /** Format: uuid */
            default_backend_id: string | null;
        };
        CredentialDetail: {
            /** Format: uuid */
            credential_id: string | null;
            s3_access_key: string;
            azure_account: string;
            access_mode: components["schemas"]["CredentialAccessMode"];
            use_managed_identity: boolean;
            versioning_enabled: boolean;
            /** Format: uuid */
            default_backend_id: string | null;
            credential_scope: string | null;
        };
        IdentityProjection: {
            /** Format: uuid */
            credential_id: string;
            s3_access_key: string;
            azure_account: string;
            access_mode: components["schemas"]["CredentialAccessMode"];
            use_managed_identity: boolean;
            versioning_enabled: boolean;
            /** Format: uuid */
            default_backend_id: string | null;
            enabled: boolean;
            virtual_bucket_count: number;
            policy_attachment_count: number;
        };
        IdentityProjectionListResponse: {
            count: number;
            items: components["schemas"]["IdentityProjection"][];
        };
        RotateCredentialSecretResponse: {
            /** Format: uuid */
            credential_id: string;
            s3_access_key: string;
            s3_secret_key: string;
        };
        CredentialListResponse: {
            count: number;
            items: components["schemas"]["CredentialSummary"][];
        };
        /** @enum {string} */
        BackendAuthMode: "managed_identity" | "account_key" | "sas_token";
        StorageBackendRequest: {
            name: string;
            azure_account: string;
            auth_mode: components["schemas"]["BackendAuthMode"];
            /** Format: uuid */
            managed_identity_client_id?: string | null;
            secret_ref?: string | null;
            /** @default false */
            user_delegation_sas_enabled: boolean;
            region_label?: string | null;
            /** @default true */
            enabled: boolean;
        };
        StorageBackendResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            azure_account: string;
            auth_mode: components["schemas"]["BackendAuthMode"];
            /** Format: uuid */
            managed_identity_client_id: string | null;
            user_delegation_sas_enabled: boolean;
            has_secret_ref: boolean;
            region_label: string | null;
            enabled: boolean;
        };
        StorageBackendList: components["schemas"]["StorageBackendResponse"][];
        CreateVirtualBucketRequest: {
            virtual_bucket_name: string;
            azure_container: string;
            /** Format: uuid */
            credential_id: string;
            /** Format: uuid */
            backend_id?: string | null;
            endpoint_prefix?: string | null;
        };
        UpdateVirtualBucketRequest: {
            enabled: boolean;
        };
        VirtualBucketResponse: {
            /** Format: uuid */
            id: string;
            virtual_bucket_name: string;
            azure_container: string;
            /** Format: uuid */
            credential_id: string;
            /** Format: uuid */
            backend_id: string | null;
            endpoint_prefix: string | null;
            enabled: boolean;
        };
        VirtualBucketList: components["schemas"]["VirtualBucketResponse"][];
        CreatePolicyRequest: {
            name: string;
            document: components["schemas"]["JsonValue"];
            description?: string | null;
        };
        UpdatePolicyRequest: {
            document?: components["schemas"]["JsonValue"] | null;
            description?: string | null;
        };
        PolicyResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            document: components["schemas"]["JsonValue"];
            description: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PolicyListResponse: {
            count: number;
            items: components["schemas"]["PolicyResponse"][];
        };
        PolicyGuardrailLimits: {
            max_attachments_per_credential: number;
            max_policy_bytes: number;
            max_policy_statements: number;
            max_compiled_bytes: number;
        };
        PolicyDocumentViolation: {
            /** @enum {string} */
            kind: "managed_policy" | "bucket_policy";
            name: string;
            json_bytes: number;
            statements: number;
            compiled_bytes: number;
            reasons: string[];
        };
        PolicyAttachmentViolation: {
            /** @constant */
            kind: "credential_policy_attachments";
            name: string;
            attachments: number;
            reasons: string[];
        };
        PolicyGuardrailViolation: components["schemas"]["PolicyDocumentViolation"] | components["schemas"]["PolicyAttachmentViolation"];
        PolicyPreflightResponse: {
            limits: components["schemas"]["PolicyGuardrailLimits"];
            count: number;
            items: components["schemas"]["PolicyGuardrailViolation"][];
        };
        AttachPolicyRequest: {
            policy_name: string;
        };
        CredentialPolicyAttachmentResponse: {
            access_key: string;
            policy_name: string;
            /** @constant */
            attached: true;
        };
        SetBucketPolicyRequest: {
            document: components["schemas"]["JsonValue"];
        };
        BucketPolicyResponse: {
            /** Format: uuid */
            credential_id: string | null;
            bucket: string;
            document: components["schemas"]["JsonValue"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SimulatePolicyRequest: {
            access_key: string;
            action: string;
            resource: string;
            /** @default {} */
            conditions: {
                [key: string]: string;
            };
        };
        SimulatePolicyResponse: {
            allowed: boolean;
            effect: string;
            matched_sid?: string;
            evaluated_policies: number;
        };
        AuditEvent: {
            /** Format: uuid */
            id: string;
            entity_type: string;
            entity_id: string;
            action: string;
            changed_by: string | null;
            changes: components["schemas"]["JsonValue"];
            /** Format: date-time */
            created_at: string;
        };
        AuditEventList: components["schemas"]["AuditEvent"][];
        CacheHealth: {
            mode: string;
            available: boolean;
            redis_connected: boolean;
        };
        CredentialHealth: {
            count: number;
        };
        MultipartHealth: {
            store_type: string;
            redis_available: boolean;
            persistence: string;
            warning: string | null;
        };
        DatabasePoolHealth: {
            max: number;
            active: number;
            idle: number;
        };
        DatabaseHealth: {
            connected: boolean;
            schema_valid: boolean;
            pool: components["schemas"]["DatabasePoolHealth"];
        };
        AuthorizationHealth: {
            /** @enum {string} */
            mode: "off" | "shadow" | "enforce";
            /** @enum {string} */
            coherence: "strict" | "bounded";
            resolver_ready: boolean;
            database_ready: boolean;
            audit_required: boolean;
            audit_dispatcher_ready: boolean;
        };
        VirtualBucketHealthReady: {
            /** @constant */
            enabled: true;
            count: number;
        };
        VirtualBucketHealthError: {
            /** @constant */
            enabled: true;
            error: string;
        };
        VirtualBucketHealth: components["schemas"]["VirtualBucketHealthReady"] | components["schemas"]["VirtualBucketHealthError"];
        AdminHealthResponse: {
            status: string;
            version: string;
            cache: components["schemas"]["CacheHealth"];
            credentials: components["schemas"]["CredentialHealth"];
            multipart: components["schemas"]["MultipartHealth"];
            /** Format: date-time */
            timestamp: string;
            database?: components["schemas"]["DatabaseHealth"];
            authorization: components["schemas"]["AuthorizationHealth"];
            virtual_buckets?: components["schemas"]["VirtualBucketHealth"];
        };
        ControlCapabilities: {
            plane: string;
            authz_mode: string;
            sts_enabled: boolean;
            iam_assume_role_enabled: boolean;
            assume_role_ready: boolean;
            iam_account_configured: boolean;
            backend_routing_enabled: boolean;
            usable_registry_auth_modes: components["schemas"]["BackendAuthMode"][];
            legacy_routing_available: boolean;
            /** Format: uri */
            public_sts_endpoint: string | null;
            /** Format: uri */
            public_s3_endpoint: string | null;
        };
        CreateIamRoleRequest: {
            account_id: string;
            /** @default / */
            role_path: string;
            role_name: string;
            /** Format: uuid */
            resource_credential_id: string;
            trust_policy: components["schemas"]["JsonValue"];
            /** @default 3600 */
            max_session_duration_seconds: number;
        };
        IamRoleResponse: {
            /** Format: uuid */
            id: string;
            role_id: string;
            account_id: string;
            role_path: string;
            role_name: string;
            role_arn: string;
            /** Format: uuid */
            resource_credential_id: string;
            trust_policy: components["schemas"]["JsonValue"];
            max_session_duration_seconds: number;
            enabled: boolean;
            lifecycle_revision: number;
            trust_revision: number;
            attachment_revision: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        IamRoleListResponse: {
            count: number;
            items: components["schemas"]["IamRoleResponse"][];
        };
        UpdateIamRoleTrustRequest: {
            trust_policy: components["schemas"]["JsonValue"];
        };
        UpdateIamRoleSettingsRequest: {
            max_session_duration_seconds: number;
        };
        SetIamRoleEnabledRequest: {
            enabled: boolean;
        };
        RetireIamRoleSessionsRequest: {
            batch_size: number;
        };
        RetireIamRoleSessionsResponse: {
            retired_sessions: number;
        };
        RolePolicyAttachmentRequest: {
            policy_name: string;
        };
        OpenApiDocument: {
            openapi?: string;
            info?: Record<string, never>;
            paths?: Record<string, never>;
        };
    };
    responses: {
        /** @description Domain/authentication errors use S3 XML. Framework extraction or routing rejections may use plain text. Status codes retain existing handler behavior. */
        ControlError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/xml": components["schemas"]["Error"];
                "text/plain": components["schemas"]["ValidationError"];
            };
        };
        /** @description Admin authentication, origin, or CSRF rejected */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/xml": components["schemas"]["Error"];
            };
        };
        /** @description Request extraction failed (malformed JSON, incompatible fields, unsupported content type, or payload too large) */
        ValidationRejected: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": components["schemas"]["ValidationError"];
            };
        };
    };
    parameters: {
        KeyName: string;
        AccessKey: string;
        Name: string;
        BucketId: string;
        Bucket: string;
        RoleId: string;
        PolicyName: string;
    };
    requestBodies: {
        CreateAdminApiKey: {
            content: {
                "application/json": components["schemas"]["CreateAdminApiKeyRequest"];
            };
        };
        UpdateAdminApiKey: {
            content: {
                "application/json": components["schemas"]["UpdateAdminApiKeyRequest"];
            };
        };
        CreateCredential: {
            content: {
                "application/json": components["schemas"]["CreateCredentialRequest"];
            };
        };
        UpdateCredential: {
            content: {
                "application/json": components["schemas"]["UpdateCredentialRequest"];
            };
        };
        StorageBackend: {
            content: {
                "application/json": components["schemas"]["StorageBackendRequest"];
            };
        };
        CreateVirtualBucket: {
            content: {
                "application/json": components["schemas"]["CreateVirtualBucketRequest"];
            };
        };
        UpdateVirtualBucket: {
            content: {
                "application/json": components["schemas"]["UpdateVirtualBucketRequest"];
            };
        };
        CreatePolicy: {
            content: {
                "application/json": components["schemas"]["CreatePolicyRequest"];
            };
        };
        UpdatePolicy: {
            content: {
                "application/json": components["schemas"]["UpdatePolicyRequest"];
            };
        };
        AttachPolicy: {
            content: {
                "application/json": components["schemas"]["AttachPolicyRequest"];
            };
        };
        SetBucketPolicy: {
            content: {
                "application/json": components["schemas"]["SetBucketPolicyRequest"];
            };
        };
        SimulatePolicy: {
            content: {
                "application/json": components["schemas"]["SimulatePolicyRequest"];
            };
        };
        CreateIamRole: {
            content: {
                "application/json": components["schemas"]["CreateIamRoleRequest"];
            };
        };
        UpdateIamRoleTrust: {
            content: {
                "application/json": components["schemas"]["UpdateIamRoleTrustRequest"];
            };
        };
        UpdateIamRoleSettings: {
            content: {
                "application/json": components["schemas"]["UpdateIamRoleSettingsRequest"];
            };
        };
        SetIamRoleEnabled: {
            content: {
                "application/json": components["schemas"]["SetIamRoleEnabledRequest"];
            };
        };
        RetireIamRoleSessions: {
            content: {
                "application/json": components["schemas"]["RetireIamRoleSessionsRequest"];
            };
        };
        RolePolicyAttachment: {
            content: {
                "application/json": components["schemas"]["RolePolicyAttachmentRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    publicHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    controlOpenApi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenApiDocument"];
                };
            };
        };
    };
    bootstrapAdminKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapAdminKeyRequest"];
            };
        };
        responses: {
            /** @description First admin key created; response is not replayable and includes Cache-Control: no-store */
            200: {
                headers: {
                    "Cache-Control": "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapAdminKeyResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Session issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    adminHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detailed health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminHealthResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Safe runtime capabilities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlCapabilities"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventList"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    listAdminKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminApiKeyList"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    createAdminKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateAdminApiKey"];
        responses: {
            /** @description Admin key created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAdminApiKeyResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    getAdminKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_name: components["parameters"]["KeyName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminApiKey"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    updateAdminKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_name: components["parameters"]["KeyName"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UpdateAdminApiKey"];
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    deleteAdminKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_name: components["parameters"]["KeyName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    listCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credentials */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialListResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    createCredential: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateCredential"];
        responses: {
            /** @description Credential created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialCreatedResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    listIdentityProjections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Identity metadata for the control UI */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityProjectionListResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    getCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_key: components["parameters"]["AccessKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credential */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialDetail"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    updateCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_key: components["parameters"]["AccessKey"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UpdateCredential"];
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialDetail"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    deleteCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_key: components["parameters"]["AccessKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    rotateCredentialSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credential_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Secret rotated and returned once */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    Pragma?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateCredentialSecretResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["ControlError"];
            default: components["responses"]["ControlError"];
        };
    };
    listBackends: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backends */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageBackendList"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    createBackend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["StorageBackend"];
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageBackendResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    getBackend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageBackendResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    updateBackend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["StorageBackend"];
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageBackendResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    deleteBackend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    listVirtualBuckets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Virtual buckets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualBucketList"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    createVirtualBucket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateVirtualBucket"];
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualBucketResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    updateVirtualBucket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: components["parameters"]["BucketId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UpdateVirtualBucket"];
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    deleteVirtualBucket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: components["parameters"]["BucketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    listPolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyListResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    createPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreatePolicy"];
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    policyPreflight: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Guardrail status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyPreflightResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    getPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    updatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UpdatePolicy"];
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    deletePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    attachPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_key: components["parameters"]["AccessKey"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["AttachPolicy"];
        responses: {
            /** @description Already attached */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialPolicyAttachmentResponse"];
                };
            };
            /** @description Attached */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialPolicyAttachmentResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    detachPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                access_key: components["parameters"]["AccessKey"];
                name: components["parameters"]["Name"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detached */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    getBucketPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket: components["parameters"]["Bucket"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketPolicyResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    setBucketPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket: components["parameters"]["Bucket"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["SetBucketPolicy"];
        responses: {
            /** @description Set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketPolicyResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    deleteBucketPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket: components["parameters"]["Bucket"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    getVirtualBucketPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: components["parameters"]["BucketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketPolicyResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    setVirtualBucketPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: components["parameters"]["BucketId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["SetBucketPolicy"];
        responses: {
            /** @description Set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketPolicyResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    deleteVirtualBucketPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: components["parameters"]["BucketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    simulatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["SimulatePolicy"];
        responses: {
            /** @description Simulation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatePolicyResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IamRoleListResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateIamRole"];
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IamRoleResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    getRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IamRoleResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
    updateRoleTrust: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UpdateIamRoleTrust"];
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IamRoleResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    updateRoleSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["UpdateIamRoleSettings"];
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IamRoleResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    setRoleEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["SetIamRoleEnabled"];
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IamRoleResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    retireRoleSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RetireIamRoleSessions"];
        responses: {
            /** @description Retired */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetireIamRoleSessionsResponse"];
                };
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    attachRolePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RolePolicyAttachment"];
        responses: {
            /** @description Attached */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ControlError"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["ValidationRejected"];
            415: components["responses"]["ValidationRejected"];
            422: components["responses"]["ValidationRejected"];
            default: components["responses"]["ControlError"];
        };
    };
    detachRolePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                role_id: components["parameters"]["RoleId"];
                policy_name: components["parameters"]["PolicyName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detached */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            default: components["responses"]["ControlError"];
        };
    };
}
