import { useState, type FormEvent, type ReactNode } from 'react'
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { BrowserRouter, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { Theme } from '@radix-ui/themes'
import { Activity, Box, ChevronRight, CircleGauge, Database, FileKey, KeyRound, LogOut, Menu, ScrollText, ServerCog, ShieldCheck, X } from 'lucide-react'
import { api, ApiError, login, logout, setCsrfToken } from './api/client'
import '@radix-ui/themes/styles.css'
import '@fontsource/manrope/latin-400.css'
import '@fontsource/manrope/latin-500.css'
import '@fontsource/manrope/latin-600.css'
import '@fontsource/manrope/latin-700.css'
import '@fontsource/ibm-plex-mono/latin-400.css'
import '@fontsource/ibm-plex-mono/latin-500.css'
import './control.css'

const queryClient = new QueryClient({ defaultOptions: { queries: { retry: 1, staleTime: 10_000 } } })
type RecordValue = Record<string, unknown>
type Field = { key: string; label: string; type?: string; required?: boolean }
type ResourceConfig = { path: string; title: string; subtitle: string; identityKey: string; defaults?: RecordValue; columns: Array<{ key: string; label: string }>; createFields?: Field[] }

const resources: Record<string, ResourceConfig> = {
  credentials: { path: '/admin/credentials', title: 'Credentials', subtitle: 'S3 identities and Azure routing defaults.', identityKey: 's3_access_key', defaults: { use_managed_identity: true, access_mode: 'direct', versioning_enabled: false }, columns: [{ key: 's3_access_key', label: 'Access key' }, { key: 'azure_account', label: 'Azure account' }, { key: 'access_mode', label: 'Mode' }, { key: 'versioning_enabled', label: 'Versioning' }], createFields: [{ key: 's3_access_key', label: 'S3 access key' }, { key: 's3_secret_key', label: 'S3 secret key', type: 'password', required: true }, { key: 'azure_account', label: 'Azure account', required: true }] },
  buckets: { path: '/admin/virtual-buckets', title: 'Virtual buckets', subtitle: 'Stable S3 names mapped to native containers.', identityKey: 'virtual_bucket_name', defaults: { backend_id: null, endpoint_prefix: null }, columns: [{ key: 'virtual_bucket_name', label: 'S3 bucket' }, { key: 'azure_container', label: 'Container' }, { key: 'credential_id', label: 'Credential' }, { key: 'enabled', label: 'Status' }], createFields: [{ key: 'virtual_bucket_name', label: 'S3 bucket', required: true }, { key: 'azure_container', label: 'Azure container', required: true }, { key: 'credential_id', label: 'Credential ID', required: true }] },
  backends: { path: '/admin/backends', title: 'Storage backends', subtitle: 'Managed Identity and secret-reference Azure backends.', identityKey: 'name', defaults: { auth_mode: 'managed_identity', user_delegation_sas_enabled: true, enabled: true, secret_ref: null, region_label: null }, columns: [{ key: 'name', label: 'Name' }, { key: 'azure_account', label: 'Azure account' }, { key: 'auth_mode', label: 'Authentication' }, { key: 'enabled', label: 'Status' }], createFields: [{ key: 'name', label: 'Name', required: true }, { key: 'azure_account', label: 'Azure account', required: true }, { key: 'auth_mode', label: 'Auth mode', required: true }] },
  policies: { path: '/admin/policies', title: 'Policies', subtitle: 'Managed IAM documents used by S3 authorization.', identityKey: 'name', columns: [{ key: 'name', label: 'Name' }, { key: 'description', label: 'Description' }, { key: 'updated_at', label: 'Updated' }], createFields: [{ key: 'name', label: 'Name', required: true }, { key: 'description', label: 'Description' }, { key: 'document', label: 'Policy document', required: true }] },
  keys: { path: '/admin/api-keys', title: 'Admin keys', subtitle: 'Automation and break-glass credentials.', identityKey: 'key_name', defaults: { created_by: 'browser-ui' }, columns: [{ key: 'key_name', label: 'Name' }, { key: 'enabled', label: 'Status' }, { key: 'last_used_at', label: 'Last used' }, { key: 'expires_at', label: 'Expires' }], createFields: [{ key: 'key_name', label: 'Name', required: true }, { key: 'description', label: 'Description' }] },
}
const navigation = [['/', 'Overview', CircleGauge], ['/credentials', 'Credentials', KeyRound], ['/buckets', 'Virtual buckets', Box], ['/backends', 'Backends', Database], ['/policies', 'Policies', ShieldCheck], ['/keys', 'Admin keys', FileKey], ['/audit', 'Audit', ScrollText], ['/health', 'Health', Activity]] as const

export default function ControlApp() {
  return <Theme accentColor="jade" grayColor="sand" radius="small"><QueryClientProvider client={queryClient}><BrowserRouter basename="/admin/ui"><Routes><Route path="/login" element={<LoginPage />} /><Route path="/*" element={<AuthenticatedApp />} /></Routes></BrowserRouter></QueryClientProvider></Theme>
}

function AuthenticatedApp() {
  const [menuOpen, setMenuOpen] = useState(false)
  const navigate = useNavigate()
  const session = useQuery({ queryKey: ['session'], queryFn: async () => { const value = await api<RecordValue>('/admin/session'); setCsrfToken(String(value.csrf_token)); return value }, retry: false })
  if (session.isError && (session.error as ApiError).status === 403) return <Navigate to="/login" replace />
  if (session.isPending) return <LoadingScreen />
  async function signOut() { await logout(); queryClient.clear(); navigate('/login', { replace: true }) }
  return <div className="shell"><aside className={menuOpen ? 'sidebar open' : 'sidebar'}><div className="brand"><ServerCog size={22} /><span>s3proxy</span><button className="icon-button close-menu" onClick={() => setMenuOpen(false)} aria-label="Close navigation"><X size={18} /></button></div><nav>{navigation.map(([to, label, Icon]) => <NavLink key={to} to={to} end={to === '/'} onClick={() => setMenuOpen(false)}><Icon size={17} /><span>{label}</span></NavLink>)}</nav><button className="sign-out" onClick={signOut}><LogOut size={16} /> Sign out</button></aside><main><header className="topbar"><button className="icon-button menu-button" onClick={() => setMenuOpen(true)} aria-label="Open navigation"><Menu size={20} /></button><div><span className="environment-dot" /> Control plane</div><span className="session-status">Session protected</span></header><Routes><Route path="/" element={<Overview />} />{Object.entries(resources).map(([key, config]) => <Route key={key} path={`/${key}`} element={<ResourcePage config={config} />} />)}<Route path="/audit" element={<AuditPage />} /><Route path="/health" element={<HealthPage />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></main></div>
}

function LoginPage() {
  const [apiKey, setApiKey] = useState('')
  const navigate = useNavigate()
  const mutation = useMutation({ mutationFn: () => login(apiKey), onSuccess: () => { queryClient.setQueryData(['session'], { authenticated: true }); setApiKey(''); navigate('/', { replace: true }) } })
  return <div className="login-page"><div className="login-mark"><ServerCog size={25} /><strong>s3proxy control</strong></div><form className="login-panel" onSubmit={(event) => { event.preventDefault(); mutation.mutate() }}><div className="eyebrow">Operator access</div><h1>Sign in</h1><p>Use an enabled admin API key. It is exchanged for a secure browser session and is never stored by this application.</p><label>Admin API key<input autoFocus type="password" autoComplete="current-password" value={apiKey} onChange={event => setApiKey(event.target.value)} required /></label>{mutation.error && <ErrorBanner error={mutation.error} />}<button className="primary" disabled={mutation.isPending}>{mutation.isPending ? 'Signing in...' : 'Continue'}<ChevronRight size={17} /></button></form></div>
}

function Overview() {
  const health = useQuery({ queryKey: ['health'], queryFn: () => api<RecordValue>('/admin/health') })
  return <Page title="Overview" subtitle="Current control-plane state and configuration inventory."><div className="metric-grid">{Object.entries(resources).slice(0, 4).map(([key, config]) => <Metric key={key} label={config.title} path={config.path} />)}</div><section className="section"><div className="section-heading"><h2>Runtime status</h2></div>{health.isError ? <ErrorBanner error={health.error} /> : <JsonSummary value={health.data} />}</section></Page>
}

function Metric({ label, path }: { label: string; path: string }) { const query = useQuery({ queryKey: [path], queryFn: () => api<unknown[]>(path) }); return <section className="metric"><span>{label}</span><strong>{Array.isArray(query.data) ? query.data.length : '-'}</strong></section> }
function ResourcePage({ config }: { config: ResourceConfig }) {
  const [creating, setCreating] = useState(false); const [oneTimeSecret, setOneTimeSecret] = useState<string | null>(null); const client = useQueryClient()
  const query = useQuery({ queryKey: [config.path], queryFn: () => api<unknown[]>(config.path) })
  const create = useMutation({ mutationFn: (body: RecordValue) => api<RecordValue>(config.path, { method: 'POST', body: JSON.stringify({ ...config.defaults, ...body }) }), onSuccess: data => { if (typeof data?.api_key === 'string') setOneTimeSecret(data.api_key); client.invalidateQueries({ queryKey: [config.path] }); setCreating(false) } })
  const remove = useMutation({ mutationFn: (identity: string) => api<void>(`${config.path}/${encodeURIComponent(identity)}`, { method: 'DELETE' }), onSuccess: () => client.invalidateQueries({ queryKey: [config.path] }) })
  return <Page title={config.title} subtitle={config.subtitle} action={config.createFields && <button className="primary" onClick={() => setCreating(true)}>Add {config.title.toLowerCase()}</button>}>{oneTimeSecret && <div className="secret-banner"><div><strong>Save this admin key now</strong><code>{oneTimeSecret}</code></div><button onClick={() => setOneTimeSecret(null)}>Dismiss</button></div>}{query.isError ? <ErrorBanner error={query.error} /> : <DataTable rows={Array.isArray(query.data) ? query.data as RecordValue[] : []} columns={config.columns} loading={query.isPending} onDelete={row => { const identity = String(row[config.identityKey]); if (window.confirm(`Delete ${identity}?`)) remove.mutate(identity) }} />}{remove.error && <ErrorBanner error={remove.error} />}{creating && config.createFields && <CreateDialog title={`Add ${config.title.toLowerCase()}`} fields={config.createFields} pending={create.isPending} error={create.error} onClose={() => setCreating(false)} onSubmit={body => create.mutate(body)} />}</Page>
}
function AuditPage() { const query = useQuery({ queryKey: ['audit'], queryFn: () => api<RecordValue[]>('/admin/audit?limit=100') }); return <Page title="Audit" subtitle="Recent append-only control-plane changes.">{query.isError ? <ErrorBanner error={query.error} /> : <DataTable loading={query.isPending} rows={query.data ?? []} columns={[{ key: 'created_at', label: 'Time' }, { key: 'entity_type', label: 'Entity' }, { key: 'action', label: 'Action' }, { key: 'changed_by', label: 'Actor' }]} />}</Page> }
function HealthPage() { const query = useQuery({ queryKey: ['health'], queryFn: () => api<RecordValue>('/admin/health'), refetchInterval: 30_000 }); return <Page title="Health" subtitle="Authenticated runtime diagnostics. Refreshes every 30 seconds.">{query.isError ? <ErrorBanner error={query.error} /> : <JsonSummary value={query.data} />}</Page> }
function Page({ title, subtitle, action, children }: { title: string; subtitle: string; action?: ReactNode; children: ReactNode }) { return <div className="page"><div className="page-heading"><div><div className="eyebrow">Administration</div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>{children}</div> }
function DataTable({ rows, columns, loading, onDelete }: { rows: RecordValue[]; columns: Array<{ key: string; label: string }>; loading: boolean; onDelete?: (row: RecordValue) => void }) { if (loading) return <div className="empty-state">Loading...</div>; if (!rows.length) return <div className="empty-state"><Box size={22} /><strong>No records</strong><span>Create a record to populate this view.</span></div>; return <div className="table-wrap"><table><thead><tr>{columns.map(column => <th key={column.key}>{column.label}</th>)}{onDelete && <th>Actions</th>}</tr></thead><tbody>{rows.map((row, index) => <tr key={String(row.id ?? row.name ?? row.key_name ?? index)}>{columns.map(column => <td key={column.key}>{display(row[column.key])}</td>)}{onDelete && <td><button className="table-action" onClick={() => onDelete(row)}>Delete</button></td>}</tr>)}</tbody></table></div> }
function CreateDialog({ title, fields, pending, error, onClose, onSubmit }: { title: string; fields: Field[]; pending: boolean; error: Error | null; onClose: () => void; onSubmit: (body: RecordValue) => void }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const body: RecordValue = {}; fields.forEach(field => { const value = form.get(field.key); if (value) body[field.key] = field.key === 'document' ? JSON.parse(String(value)) : value }); onSubmit(body) }; return <div className="dialog-backdrop"><form className="dialog" onSubmit={submit}><div className="dialog-heading"><h2>{title}</h2><button type="button" className="icon-button" onClick={onClose} aria-label="Close"><X size={18} /></button></div>{fields.map(field => <label key={field.key}>{field.label}{field.key === 'document' ? <textarea name={field.key} required={field.required} rows={8} defaultValue={'{"Version":"2012-10-17","Statement":[]}'} /> : <input name={field.key} type={field.type ?? 'text'} required={field.required} />}</label>)}{error && <ErrorBanner error={error} />}<div className="dialog-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={pending}>{pending ? 'Saving...' : 'Save'}</button></div></form></div> }
function JsonSummary({ value }: { value: unknown }) { return value ? <pre className="json-summary">{JSON.stringify(value, null, 2)}</pre> : <div className="empty-state">Loading...</div> }
function ErrorBanner({ error }: { error: unknown }) { return <div className="error-banner">{error instanceof Error ? error.message : 'Request failed'}</div> }
function LoadingScreen() { return <div className="loading-screen"><ServerCog size={24} /> Loading control plane...</div> }
function display(value: unknown) { if (value === null || value === undefined || value === '') return '-'; if (typeof value === 'boolean') return value ? 'Enabled' : 'Disabled'; if (typeof value === 'object') return JSON.stringify(value); return String(value) }
